displayName: Check Header
type: middleware

import: github.com/lootwich/checkheader

summary: 'Checks if the header contains a value like a group'

testData:
  GroupHeaderName: "X-Demo"
  NeededGroups:
    - "test"
    - "example"
